### ISSUE TITLE
Infinite Series

### ISSUE THREAD

**Issue by arnavs** [JuliaMath/Richardson.jl#10]
(Revision of earlier comment)

Hi @stevengj,

I've seen some threads on the use of this package to evaluate infinite series. But I'm not sure how that would go, since the thing we're sending to infinity is discrete... and I'm seeing the related errors (e.g., `InexactError: trunc(Int64, Inf)`)

Any thoughts? Is there any documentation on that use case?

**Comment by arnavs** [comment]
Actually closing this, I think it reduces to #4.

**Comment by stevengj** [comment]
Should be fixed in version 1.4.1 (https://github.com/JuliaRegistries/General/pull/93656)

**Comment by stevengj** [comment]
That being said, realize that Richardson extrapolation works by fitting to polynomials as [explained here](https://github.com/JuliaMath/Richardson.jl#infinite-limits), so it's not clear to me how well this would work for integer-valued sequences.

**Comment by arnavs** [comment]
Hi @stevengj, my thought was that I could take the limit of the partial sums with the `contract` parameter as some integer reciprocal. If the function represented by the sum is analytic, maybe this would work... 

The hope is that this would be better than just iterating on the partial sums until they're within epsilon of each other.

**Comment by stevengj** [comment]
Yes, you could certainly try that.  Would love to hear how well it works!
